# Generated by Django 6.0.3 on 2026-03-10 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='anime_poster')),
                ('description', models.TextField()),
                ('release_year', models.DateField(verbose_name='Дата')),
                ('shikimori_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('our_rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_color', models.CharField(choices=[('Красный', '🔴 Красный'), ('Оранжевый', '🟠 Оранжевый'), ('Жёлтый', '🟡 Жёлтый'), ('Зелёный', '🟢 Зелёный'), ('Синий', '🔵 Синий'), ('Фиолетовый', '🟣 Фиолетовый'), ('Коричневый', '🟤 Коричневый'), ('Чёрный', '⚫️ Чёрный'), ('Белый', '⚪️ Белый')], max_length=20)),
                ('hair_color', models.CharField(choices=[('Красный', '🔴 Красный'), ('Оранжевый', '🟠 Оранжевый'), ('Жёлтый', '🟡 Жёлтый'), ('Зелёный', '🟢 Зелёный'), ('Синий', '🔵 Синий'), ('Фиолетовый', '🟣 Фиолетовый'), ('Коричневый', '🟤 Коричневый'), ('Чёрный', '⚫️ Чёрный'), ('Белый', '⚪️ Белый')], max_length=20)),
                ('gender', models.CharField(choices=[('Мужской', '♂️ Мужской'), ('Женский', '♀️ Женский'), ('Неизвестно', '❓ Неизвестно')], max_length=20)),
                ('species', models.CharField(choices=[('Человек', 'Человек'), ('Демон', 'Демон'), ('Ангел', 'Ангел'), ('Гном', 'Гном'), ('Эльф', 'Эльф')], max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('gg', models.CharField(blank=True, choices=[('Главный герой', '⭐ Главный герой')], default=None, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='characters/')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='films', to='core.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='animes', to='core.genre'),
        ),
        migrations.CreateModel(
            name='SeasonAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasons_number', models.PositiveIntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('episode_number', models.PositiveIntegerField()),
                ('video', models.FileField(upload_to='episodes/')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.seasonanime')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Буду смотреть'), ('watched', 'Просмотрено')], max_length=10)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'anime')},
            },
        ),
        migrations.CreateModel(
            name='Reating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(choices=[('1', '⭐1'), ('2', '⭐2'), ('3', '⭐3'), ('4', '⭐4'), ('5', '⭐5')], max_length=5)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
