# Generated by Django 6.0.3 on 2026-03-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='anime_poster')),
                ('description', models.TextField()),
                ('release_year', models.DateField(verbose_name='Дата')),
                ('shikimori_rating', models.PositiveIntegerField()),
                ('our_rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_color', models.CharField(choices=[('Чёрный', 'Чёрный')])),
                ('hair_color', models.CharField()),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Неизвестно', 'Неизвестно')])),
                ('species', models.CharField()),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField()),
                ('gg', models.CharField(blank=True, choices=[('Главный герой', 'Главный герой')], default='True', null=True)),
                ('image', models.ImageField(upload_to='characters/')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='core.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='films', to='core.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='animes', to='core.genre'),
        ),
        migrations.CreateModel(
            name='SeasonAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasons_number', models.PositiveIntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('episode_number', models.PositiveIntegerField()),
                ('video', models.FileField(upload_to='episodes/')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.seasonanime')),
            ],
        ),
    ]
