# Generated by Django 6.0.3 on 2026-03-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='anime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='core.anime'),
            preserve_default=False,
        ),
    ]
