# Generated by Django 6.0.3 on 2026-03-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_character_eye_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='hair_color',
            field=models.CharField(choices=[('Чёрный', 'Чёрный'), ('Синий', 'Синий'), ('Жёлтый', 'Жёлтый'), ('Красный', 'Красный'), ('Зелёный', 'Зелёный'), ('Фиолетывый', 'Фиолетывыё')]),
        ),
    ]
