# Generated by Django 6.0.3 on 2026-03-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_anime_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.CharField(choices=[('Человек', 'Человек'), ('Демон', 'Демон'), ('Ангел', 'Ангел'), ('Гном', 'Гном'), ('Эльф', 'Эльф'), ('Неизвестно', 'Неизвестно')], max_length=20),
        ),
    ]
