# Generated by Django 6.0.3 on 2026-03-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_character_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='ss_year',
            field=models.CharField(default='spring'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
