# Generated by Django 6.0.3 on 2026-03-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_anime_ss_year_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='ss_year',
            field=models.CharField(default='Весна'),
        ),
    ]
